name: prueba_helipagos_mobile
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter_test:
    sdk: flutter
  connectivity_plus: ^6.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  http: ^1.2.2
  json_annotation: ^4.9.0
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  bloc_test: ^9.1.7
  flutter_staggered_grid_view: ^0.7.0
  logger: ^2.4.0
  cached_network_image: ^3.4.1
  path_provider: ^2.1.5
  flutter_html: ^3.0.0-beta.2
  flutter_launcher_icons: ^0.14.1

dev_dependencies:
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/logo.png

flutter_launcher_icons:
  image_path: "assets/img/logo.png"
  android: true
  ios: true
  remove_alpha_ios: true
